### ISSUE TITLE
Hadoop 2.8.4

### ISSUE THREAD

**Issue by mateuszboryn** [steveloughran/winutils#15]
Could you please kindly provide build for hadoop 2.8.4? Using winutils 2.8.3 with hadoop jars 2.8.4 seems causing problems like this:
```
18/11/07 10:32:37 WARN SharedState: URL.setURLStreamHandlerFactory failed to set FsUrlStreamHandlerFactory

A needed class was not found. This could be due to an error in your runpath. Missing class: org/apache/hadoop/crypto/key/KeyProviderTokenIssuer
java.lang.NoClassDefFoundError: org/apache/hadoop/crypto/key/KeyProviderTokenIssuer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:2762)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2789)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2810)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2849)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2831)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.liftedTree1$1(InMemoryCatalog.scala:111)
	at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.doCreateDatabase(InMemoryCatalog.scala:109)
	at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.createDatabase(ExternalCatalog.scala:69)
	at org.apache.spark.sql.internal.SharedState.externalCatalog$lzycompute(SharedState.scala:117)
	at org.apache.spark.sql.internal.SharedState.externalCatalog(SharedState.scala:102)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.catalog$lzycompute(BaseSessionStateBuilder.scala:133)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.catalog(BaseSessionStateBuilder.scala:131)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anon$1.<init>(BaseSessionStateBuilder.scala:157)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.analyzer(BaseSessionStateBuilder.scala:157)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:79)
	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:74)
	at org.apache.spark.sql.SparkSession.internalCreateDataFrame(SparkSession.scala:578)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:597)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:352)
...
```
Also AWS EMR users are bound to certain versions of hadoop, that's why this is an issue.

**Comment by steveloughran** [comment]
AWS EMR is closed source. I can't do anything related to building that as I don't know what they've cherry picked in. 

That said, I'll try and do an ASF 2.8.4 build

**Comment by mateuszboryn** [comment]
Great, that should be just enough to get it working.

**Comment by cdarlint** [comment]
@mateuszboryn take a look at https://github.com/cdarlint/winutils

**Comment by mateuszboryn** [comment]
Great! Thanks.

**Comment by steveloughran** [comment]
WONTFIX, sorry. I'm not set up to build windows binaries any more

I'd prefer someone removed the need for it entirely [HADOOP-13223. winutils.exe is a bug nexus and should be killed with an axe.](https://issues.apache.org/jira/browse/HADOOP-13223).

Pull requests welcome there.
