### ISSUE TITLE
64Bit version of this tool

### ISSUE THREAD

**Issue by ziaul-haque** [steveloughran/winutils#3]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd\

C:\>cd spark-2.0.2-bin-hadoop2.7\bin

C:\spark-2.0.2-bin-hadoop2.7\bin>winutils.exe
Usage: winutils.exe [command] ...
Provide basic command line utilities for Hadoop on Windows.

The available commands and their usages are:

chmod          Change file mode bits.

Usage: chmod [OPTION] OCTAL-MODE [FILE]
   or: chmod [OPTION] MODE [FILE]
Change the mode of the FILE to MODE.

   -R: change files and directories recursively

Each MODE is of the form '[ugoa]*([-+=]([rwxX]*|[ugo]))+'.

chown          Change file owner.

Usage: chown [OWNER][:[GROUP]] [FILE]
Change the owner and/or group of the FILE to OWNER and/or GROUP.

Note:
On Linux, if a colon but no group name follows the user name, the group of
the files is changed to that user's login group. Windows has no concept of
a user's login group. So we do not change the group owner in this case.

groups         List user groups.

Usage: groups [OPTIONS] [USERNAME]
Print group information of the specified USERNAME (the current user by default).

OPTIONS: -F format the output by separating tokens with a pipe

hardlink       Hard link operations.

Usage: hardlink create [LINKNAME] [FILENAME] |
       hardlink stat [FILENAME]
Creates a new hardlink on the existing file or displays the number of links
for the given file

ls             List file information.

Usage: ls [OPTIONS] [FILE]
List information about the FILE (the current directory by default).
Using long listing format and list directory entries instead of contents,
and do not dereference symbolic links.
Provides equivalent or similar function as 'ls -ld' on GNU/Linux.

OPTIONS: -L dereference symbolic links
         -F format the output by separating tokens with a pipe

symlink   Create a symbolic link.

Usage: symlink [LINKNAME] [FILENAME]
Creates a symbolic link

0 is returned on success.
2 is returned if the user does no have privilege to create symbolic links.
1 is returned for all other errors.

The default security settings in Windows disallow non-elevated administrators
and all non-administrators from creating symbolic links. The security settings
for symbolic links can be changed in the Local Security Policy management
console.

readlink  Print the target of a symbolic link.

Usage: readlink [LINKNAME]
Prints the target of a symbolic link
The output and returned error codes are similar to the UNIX
readlink command. However no options are accepted.

0 is returned on success.
1 is returned for all errors.

systeminfo     System information.

    Usage: systeminfo
    Prints machine information on stdout
    Comma separated list of the following values.
    VirtualMemorySize(bytes),PhysicalMemorySize(bytes),
    FreeVirtualMemory(bytes),FreePhysicalMemory(bytes),
    NumberOfProcessors,CpuFrequency(Khz),
    CpuTime(MilliSec,Kernel+User)

task           Task operations.

    Usage: task create [TASKNAME] [COMMAND_LINE] |
          task createAsUser [TASKNAME] [USERNAME] [PIDFILE] [COMMAND_LINE] |
          task isAlive [TASKNAME] |
          task kill [TASKNAME]
          task processList [TASKNAME]
    Creates a new task jobobject with taskname
    Creates a new task jobobject with taskname as the user provided
    Checks if task jobobject is alive
    Kills task jobobject
    Prints to stdout a list of processes in the task
    along with their resource usage. One process per line
    and comma separated info per process
    ProcessId,VirtualMemoryCommitted(bytes),
    WorkingSetSize(bytes),CpuTime(Millisec,Kernel+User)
service        Service operations.

    Usage: service
    Starts the nodemanager Windows Secure Container Executor helper service.
    The service must run as a high privileged account (LocalSystem)
    and is used by the nodemanager WSCE to spawn secure containers on Windows.

C:\spark-2.0.2-bin-hadoop2.7\bin>winutils.exe start
Usage: winutils.exe [command] ...
Provide basic command line utilities for Hadoop on Windows.

The available commands and their usages are:

chmod          Change file mode bits.

Usage: chmod [OPTION] OCTAL-MODE [FILE]
   or: chmod [OPTION] MODE [FILE]
Change the mode of the FILE to MODE.

   -R: change files and directories recursively

Each MODE is of the form '[ugoa]*([-+=]([rwxX]*|[ugo]))+'.

chown          Change file owner.

Usage: chown [OWNER][:[GROUP]] [FILE]
Change the owner and/or group of the FILE to OWNER and/or GROUP.

Note:
On Linux, if a colon but no group name follows the user name, the group of
the files is changed to that user's login group. Windows has no concept of
a user's login group. So we do not change the group owner in this case.

groups         List user groups.

Usage: groups [OPTIONS] [USERNAME]
Print group information of the specified USERNAME (the current user by default).

OPTIONS: -F format the output by separating tokens with a pipe

hardlink       Hard link operations.

Usage: hardlink create [LINKNAME] [FILENAME] |
       hardlink stat [FILENAME]
Creates a new hardlink on the existing file or displays the number of links
for the given file

ls             List file information.

Usage: ls [OPTIONS] [FILE]
List information about the FILE (the current directory by default).
Using long listing format and list directory entries instead of contents,
and do not dereference symbolic links.
Provides equivalent or similar function as 'ls -ld' on GNU/Linux.

OPTIONS: -L dereference symbolic links
         -F format the output by separating tokens with a pipe

symlink   Create a symbolic link.

Usage: symlink [LINKNAME] [FILENAME]
Creates a symbolic link

0 is returned on success.
2 is returned if the user does no have privilege to create symbolic links.
1 is returned for all other errors.

The default security settings in Windows disallow non-elevated administrators
and all non-administrators from creating symbolic links. The security settings
for symbolic links can be changed in the Local Security Policy management
console.

readlink  Print the target of a symbolic link.

Usage: readlink [LINKNAME]
Prints the target of a symbolic link
The output and returned error codes are similar to the UNIX
readlink command. However no options are accepted.

0 is returned on success.
1 is returned for all errors.

systeminfo     System information.

    Usage: systeminfo
    Prints machine information on stdout
    Comma separated list of the following values.
    VirtualMemorySize(bytes),PhysicalMemorySize(bytes),
    FreeVirtualMemory(bytes),FreePhysicalMemory(bytes),
    NumberOfProcessors,CpuFrequency(Khz),
    CpuTime(MilliSec,Kernel+User)

task           Task operations.

    Usage: task create [TASKNAME] [COMMAND_LINE] |
          task createAsUser [TASKNAME] [USERNAME] [PIDFILE] [COMMAND_LINE] |
          task isAlive [TASKNAME] |
          task kill [TASKNAME]
          task processList [TASKNAME]
    Creates a new task jobobject with taskname
    Creates a new task jobobject with taskname as the user provided
    Checks if task jobobject is alive
    Kills task jobobject
    Prints to stdout a list of processes in the task
    along with their resource usage. One process per line
    and comma separated info per process
    ProcessId,VirtualMemoryCommitted(bytes),
    WorkingSetSize(bytes),CpuTime(Millisec,Kernel+User)
service        Service operations.

    Usage: service
    Starts the nodemanager Windows Secure Container Executor helper service.
    The service must run as a high privileged account (LocalSystem)
    and is used by the nodemanager WSCE to spawn secure containers on Windows.

C:\spark-2.0.2-bin-hadoop2.7\bin>spark-shell
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
16/11/22 17:44:50 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:379)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:394)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:387)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.findHadoopBinary(HiveConf.java:2327)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:365)
        at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:105)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:228)
        at org.apache.spark.sql.SparkSession$.hiveClassesArePresent(SparkSession.scala:963)
        at org.apache.spark.repl.Main$.createSparkSession(Main.scala:91)
        at $line3.$read$$iw$$iw.<init>(<console>:15)
        at $line3.$read$$iw.<init>(<console>:31)
        at $line3.$read.<init>(<console>:33)
        at $line3.$read$.<init>(<console>:37)
        at $line3.$read$.<clinit>(<console>)
        at $line3.$eval$.$print$lzycompute(<console>:7)
        at $line3.$eval$.$print(<console>:6)
        at $line3.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
        at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply$mcV$sp(SparkILoop.scala:38)
        at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
        at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
        at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
        at org.apache.spark.repl.SparkILoop.initializeSpark(SparkILoop.scala:37)
        at org.apache.spark.repl.SparkILoop.loadFiles(SparkILoop.scala:94)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:920)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at org.apache.spark.repl.Main$.doMain(Main.scala:68)
        at org.apache.spark.repl.Main$.main(Main.scala:51)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/11/22 17:44:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/11/22 17:44:52 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Spark context Web UI available at http://192.168.0.23:4040
Spark context available as 'sc' (master = local[*], app id = local-1479816891834).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.2
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)
Type in expressions to have them evaluated.
Type :help for more information.

scala>

**Comment by cricket007** [comment]
64 bit version of the tool is not the issue. 

```
ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```

It seems you have not set a `HADOOP_HOME` environment variable to `C:\spark-2.0.2-bin-hadoop2.7`

**Comment by steveloughran** [comment]
yeah, it's that `null\bin\winutils.exe` error. I've tried to make it more useful in Hadoop 2.8, though I fear that I've just changed the meaningless error to one differently bad
